version: "3.5"

services:
  referenceimplementation:
    image: nsg/referenceimplementation:latest
    depends_on:
      - postgres
    restart: always
    ports:
      - 127.0.0.1:8080:8080
    environment:
      - NSG_POSTGRES_DB_URL
      - NSG_POSTGRES_DBO_USER
      - NSG_POSTGRES_DBO_PASSWORD
      - NSG_POSTGRES_USER
      - NSG_POSTGRES_PASSWORD
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
