postgres:
  nsg:
    db_url: ${NSG_POSTGRES_DB_URL:jdbc:postgresql://postgres:5432/postgres?currentSchema=nsg&sslmode=prefer}
    dbo_user: ${NSG_POSTGRES_DBO_USER:postgres}
    dbo_password: ${NSG_POSTGRES_DBO_PASSWORD:password}
    user: ${NSG_POSTGRES_USER:postgres}
    password: ${NSG_POSTGRES_PASSWORD:password}

server:
  compression:
    enabled: true
    mime-types: application/xml,application/json,text/plain
  http2:
    enabled: true

#spring:
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration

#Enable this to log REST API mappings (GCP health probe will spam the log, though)
#logging:
#  level:
#    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE

---
spring.profiles: local
postgres:
  nsg:
    db_url: ${NSG_POSTGRES_DB_URL:jdbc:postgresql://localhost:5432/nsg_db}
    dbo_user: ${NSG_POSTGRES_DBO_USER:nsg}
    dbo_password: ${NSG_POSTGRES_DBO_PASSWORD:Passw0rd}
    user: ${NSG_POSTGRES_USER:nsg}
    password: ${NSG_POSTGRES_PASSWORD:Passw0rd}