postgres:
  nsg:
    db_url: ${NSG_POSTGRES_DB_URL:jdbc:postgresql://postgres:5432/postgres?currentSchema=nsg&sslmode=prefer}
    dbo_user: ${NSG_POSTGRES_DBO_USER:postgres}
    dbo_password: ${NSG_POSTGRES_DBO_PASSWORD:password}
    user: ${NSG_POSTGRES_USER:postgres}
    password: ${NSG_POSTGRES_PASSWORD:password}
